version: '3'

services:
  database:
    image: mysql:8
    environment:
      MYSQL_DATABASE: app
      MYSQL_PASSWORD: ChangeMe
      MYSQL_ROOT_PASSWORD: ChangeMe
      MYSQL_USER: symfony
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
  
  adminer:
    image: adminer
    ports:
      - 8080:8080